name: Environment variable Test

on:
  push:
    branches: [main]

# env:
#     NAME: value

jobs:
  modify-json:
    name: Update json file via Python
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo for use
        uses: actions/checkout@v3
        with:
          # repository: universallyleo/ngzkHandshakeScrape
          ref: main
        # token: ${{ secrets.GITHUB_TOKEN }}
        # path: ${{ env.DEVOPS_DIR }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # install the python version needed

      - name: Install python packages
        run: pip install -r requirements.txt

      - name: Run Python # run main.py
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: python envTest.py
