name: Update JSON weekly

on:
  schedule:
    - cron: "30 8 * * THU"
    #- cron: '5 5 * * THU'
#on:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]

# env:
#     NAME: value

jobs:
  modify-json:
    name: Update json file via Python
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo for use
        uses: actions/checkout@v3
        with:
          # repository: universallyleo/ngzkHandshakeScrape
          ref: main
        # token: ${{ secrets.GITHUB_TOKEN }}
        # path: ${{ env.DEVOPS_DIR }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # install the python version needed

      - name: Install python packages
        run: pip install -r requirements.txt

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Copy original json
        run: mv ./src/lib/data/data.json ./src/lib/data/old/data_${{ env.today }}.json

      - name: Scrape with Python # run main.py
        env:
          COOKIES: ${{ secrets.FORTUNE_COOKIES }}
        run: python scrape.py old/data_${{ env.today }}.json

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Github Action auto update on ${{ env.today }}
